name: IINACT_CN build

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: '0.0.0.0'
      DALAMUD_HOME: /tmp/dalamud
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    - name: Download Dalamud
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
        Expand-Archive -Force latest.zip /tmp/dalamud
    - name: Build
      run: dotnet build -c release
    - name: Prepare Build Artifact
      shell: pwsh
      run: |
        Copy-Item "IINACT/bin/Release/win-x64/IINACT_CN/latest.zip" -Destination "IINACT_CN.zip"
        Expand-Archive -Force IINACT_CN.zip Artifact
    - name: Upload IINACT
      uses: actions/upload-artifact@v4
      with:
        name: IINACT_CN
        path: Artifact/*
    - name: Update repo.json if needed
      shell: pwsh
      run: |
        $repoJsonPath = 'repo.json'
        $repoJson = Get-Content $repoJsonPath -Raw
        $repo = $repoJson | ConvertFrom-Json
        $build = Get-Content 'IINACT/bin/Release/win-x64/IINACT_CN/IINACT_CN.json' -raw | ConvertFrom-Json
        $releaseVersion = $build.AssemblyVersion
        if ([string]::IsNullOrWhiteSpace($releaseVersion)) {
          throw 'The build manifest does not contain an AssemblyVersion.'
        }
        Write-Output "REPO_JSON_VERSION=$releaseVersion" >> $env:GITHUB_ENV

        if ($repo.AssemblyVersion -ne $releaseVersion) {
          Write-Output "RELEASE_VERSION=$releaseVersion" >> $env:GITHUB_ENV
        }

        $releaseUrl = 'https://github.com/${{ github.repository }}/releases/download/v' + $releaseVersion + '/IINACT_CN.zip'
        $repo.AssemblyVersion = $releaseVersion
        $repo.TestingAssemblyVersion = $releaseVersion
        $repo.DownloadLinkInstall = $releaseUrl
        $repo.DownloadLinkTesting = $releaseUrl
        $repo.DownloadLinkUpdate = $repo.DownloadLinkInstall

        $updatedRepoJson = $repo | ConvertTo-Json -Depth 10 | ForEach-Object { "[`n" + $_ + "`n]" }
        if ($repoJson -eq $updatedRepoJson) {
          Exit
        }

        $updatedRepoJson | Set-Content $repoJsonPath -Encoding utf8 -NoNewline
        Write-Output 'REPO_JSON_CHANGED=true' >> $env:GITHUB_ENV
    - name: Create Release
      if: ${{ env.RELEASE_VERSION != '0.0.0.0' }}
      uses: softprops/action-gh-release@v1
      with:
        files: IINACT_CN.zip
        name: IINACT_CN ${{ env.RELEASE_VERSION }}
        tag_name: v${{ env.RELEASE_VERSION }}
        prerelease: false
        append_body: true
        body_path: .github/release-notices.md
        generate_release_notes: true
        fail_on_unmatched_files: true
    - name: Commit repo.json
      if: ${{ env.REPO_JSON_CHANGED == 'true' }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add repo.json
        git diff --cached --quiet && exit 0
        git commit -m "[CI] updating repo.json for ${{ env.REPO_JSON_VERSION }}"
        git push
    
    

